# Generated by Django 4.1.6 on 2023-02-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Сотувчи корхона', 'verbose_name_plural': 'Сотувчи корхоналар'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техникалар'},
        ),
        migrations.AlterModelOptions(
            name='handler',
            options={'verbose_name': 'Маъсул ҳодим', 'verbose_name_plural': 'Маъсул ҳодимлар'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Маъсул бўлим', 'verbose_name_plural': 'Маъсул бўлимлар'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тури', 'verbose_name_plural': 'Тури'},
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='Сотувчи корхона контакти'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Сотувчи корхона номи'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Document',
            field=models.FileField(upload_to='documents/', verbose_name='Хужжат юклаш (Шартнома, чек ва ҳ.к)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Service',
            field=models.CharField(max_length=200, verbose_name='Техник холати, хизмат кўрсатиш, алохида холатлар'),
        ),
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.company', verbose_name='Сотувчи корхона'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(verbose_name='Маълумот'),
        ),
        migrations.AlterField(
            model_name='device',
            name='guarranty',
            field=models.IntegerField(verbose_name='кафолат муддати'),
        ),
        migrations.AlterField(
            model_name='device',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.handler', verbose_name='Маъсул ходим'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inventar',
            field=models.IntegerField(verbose_name='Инвентар рақами'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, verbose_name='номи'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.IntegerField(verbose_name='нархи'),
        ),
        migrations.AlterField(
            model_name='device',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.structure', verbose_name='Маъсул бўлим'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.type', verbose_name='тури'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Маъсул ҳодим ФИО'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Маъсул бўлим номи'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тури'),
        ),
    ]
