# Generated by Django 4.1.6 on 2023-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_company_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bought',
            field=models.DateField(blank=True, null=True, verbose_name='сана'),
        ),
    ]
