# Generated by Django 4.1.6 on 2023-08-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_bought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Service',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Document',
        ),
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='device',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Хужжат юклаш (Шартнома, чек ва ҳ.к)'),
        ),
    ]
