# Generated by Django 4.1.6 on 2023-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_service_device_service_remove_device_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
